version: '3'

services:
  postgres:
    image: postgres:13.1
    container_name: typeormtest_db
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
